// This is an autogenerated config file, any changes to this file will be overwritten

#ifndef SLI_MBEDTLS_CONFIG_AUTOGEN_H
#define SLI_MBEDTLS_CONFIG_AUTOGEN_H



#define MBEDTLS_AES_C
#define MBEDTLS_THREADING_C
#define MBEDTLS_THREADING_ALT
#define MBEDTLS_PSA_CRYPTO_CONFIG






#endif // SLI_MBEDTLS_CONFIG_AUTOGEN_H
